services:
  web:
    build:
        context: ./api
        dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --reload'
    # volumes:
    #   - ./api:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://ctf:ctf@db:5432/ctf
      - DB_NAME=ctf
      - DB_USER=ctf
      - DB_PASS=ctf
      - DB_HOST=db
      - DB_PORT=5432
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - SECRET_KEY=f269c7bbce9dae5f655d655777873e6dd78d5074c3271adeef8dbcb1ce57230b
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ctf
      - POSTGRES_PASSWORD=ctf
      - POSTGRES_DB=ctf
      - DB_NAME=ctf
      - DB_USER=ctf
      - DB_PASS=ctf
      - DB_HOST=db
      - DB_PORT=5432
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - SECRET_KEY=f269c7bbce9dae5f655d655777873e6dd78d5074c3271adeef8dbcb1ce57230b

volumes:
  postgres_data: